name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.101
      - name: Get Submodules
        run: git submodule init && git submodule update --recursive --init
      - name: Build Tortuga Library
        run: sh restore.sh
      - name: Build with dotnet
        run: dotnet build --configuration Release TortugaEditor.csproj
